from django.urls import path
from . import views
from .views import *


urlpatterns = [
	path('', home,name='home'),
	path('viewcompany',viewcompany,name='viewcompany'),
	path('viewstudent',viewstudent,name='viewstudent'),
	path('student_edit/<int:pk>', student_update, name='student_edit'),
	path('student_delete/<int:pk>', student_delete, name='student_delete'),
	path('student_create', student_create, name='student_create'),
	path('company_create', company_create, name='company_create'),
	path('company_edit/<int:pk>', company_update, name='company_edit'),
	path('company_delete/<int:pk>', company_delete, name='company_delete'),
	path('company_select/<int:pk>', company_select, name='company_select'),
	path('place_student',place_student,name='place_student'),
	path('change_password',change_password,name='change_password'),
	path('import_credential',import_credential,name='import_credential'),
	path('export_credential',export_credential,name='export_credential'),
	path('my_profile',my_profile,name='my_profile'),
	path('student_profile/<int:pk>',student_profile,name='student_profile'),
	path('company_profile/<int:pk>',company_profile,name='company_profile'),
	path('upload_document',upload_document,name='upload_document'),
	path('folders_list',folders_list,name='folders_list'),
	path('files_list/<folder_name>',files_list,name='files_list'),
	path('download_files/<folder_name>/<file_name>',download_files,name='download_files'),
	path('search_student',search_student,name='search_student'),
	path('search_company',search_company,name='search_company'),
	path('post', post_create, name='post'),
	path('announcement_list',announcement_list.as_view(), name='announcement_list'),
	path('<slug:slug>/', views.announcement_detail.as_view(), name='post_detail'),
	path('current_users', get_current_users, name='current_users'),
	path('other_utilities', other_utilities, name='other_utilities'),
	path('export_student_csv', export_student_csv, name='export_student_csv'),
	path('import_student_data', import_student_data, name='import_student_data'),
	path('suggested_company', suggested_company, name='suggested_company'),
	path('my_company', my_company, name='my_company'),
	path('placement', placement, name='placement'),
	path('reset_profiles', reset_profiles, name='reset_profiles'),
	path('reset_app', reset_app, name='reset_app'),
	path('generate_placement_report', generate_placement_report, name='generate_placement_report'),
	path('export_company_csv', export_company_csv, name='export_company_csv'),
	path('import_company_data', import_company_data, name='import_company_data'),
	path('placed_students', placed_students, name='placed_students'),
]