# Generated by Django 3.0.5 on 2020-05-06 15:55

import Training_and_Placement_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('criteria', models.FloatField(blank=True, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('hired_count', models.IntegerField(blank=True, null=True)),
                ('required_recruitment', models.IntegerField()),
                ('other_details', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_id', models.IntegerField(blank=True, null=True)),
                ('cmp_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=500, null=True)),
                ('HSC_board', models.CharField(blank=True, max_length=500, null=True)),
                ('HSC_year', models.CharField(blank=True, max_length=100, null=True)),
                ('HSC_marks', models.FloatField(blank=True, null=True)),
                ('HSC_school_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('SSC_board', models.CharField(blank=True, max_length=500, null=True)),
                ('SSC_year', models.CharField(blank=True, max_length=100, null=True)),
                ('SSC_marks', models.FloatField(blank=True, null=True)),
                ('SSC_school_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('active_back', models.IntegerField(default=0)),
                ('passive_back', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, default='B.TECH', max_length=10, null=True)),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('university', models.CharField(blank=True, max_length=1000, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=100, null=True)),
                ('CGPA', models.FloatField()),
                ('placed', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=Training_and_Placement_app.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
