# Generated by Django 3.0.5 on 2020-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
