# Generated by Django 3.0.5 on 2020-05-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0003_auto_20200507_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='criteria',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(blank=True, default='ICT', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, default='Ganpat University', max_length=1000, null=True),
        ),
    ]
