# Generated by Django 3.0.5 on 2020-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0004_auto_20200507_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placed_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
