# Generated by Django 3.0.5 on 2020-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0005_student_placed_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_back',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passive_back',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
