# Generated by Django 3.0.5 on 2020-05-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0006_auto_20200507_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placed_company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='cmp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Training_and_Placement_app.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggested',
            name='std_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Training_and_Placement_app.Student'),
            preserve_default=False,
        ),
    ]
