# Generated by Django 3.0.5 on 2020-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0009_auto_20200508_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
