# Generated by Django 3.0.5 on 2020-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_and_Placement_app', '0010_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hired_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
